#!/command/with-contenv sh

DP_CONF="/usr/local/etc/haproxy/dataplaneapi.yml"

if grep -q "password: admin" "${DP_CONF}"; then
    echo "Generated admin password for Dataplaneapi"

    PASS=$(tr -cd 'A-Za-z0-9!?%=' < /dev/urandom | head -c8)
    sed -i "s,password: admin,password: ${PASS},g" "${DP_CONF}"
fi

SERVICE_DIRS="/run/s6-rc/servicedirs"
HAP_CONF="/usr/local/etc/haproxy/haproxy.cfg"

if grep -q "user admin insecure-password admin" "${HAP_CONF}"; then
    echo "Generated admin password for Dataplaneapi"

    PASS=$(tr -cd 'A-Za-z0-9!?%=' < /dev/urandom | head -c8)
    sed -i "s,user admin insecure-password admin,user admin insecure-password ${PASS},g" "${HAP_CONF}"

    /package/admin/s6/command/s6-svc -2 "${SERVICE_DIRS}/haproxy"
fi

MEMLIMIT=$(free -m | awk '/Mem:/ {printf "%d\n", int($2 / 3)}')

CG_LIMIT_FILE="/sys/fs/cgroup/memory/memory.limit_in_bytes"
if [ -f "/sys/fs/cgroup/cgroup.controllers" ]; then
    CG_LIMIT_FILE="/sys/fs/cgroup/memory.max"
fi

if [ -r "${CG_LIMIT_FILE}" ]; then
    if grep -q '^max$' "${CG_LIMIT_FILE}"; then
        MEMLIMIT_CG="${MEMLIMIT}"
    else
        MEMLIMIT_CG=$(awk '{printf "%d\n", int($1 / 1024 / 1024 / 3)}' "${CG_LIMIT_FILE}")
    fi

    if [ "${MEMLIMIT_CG}" -gt 0 ]; then
        if [ "${MEMLIMIT_CG}" -lt "${MEMLIMIT}" ]; then
            MEMLIMIT="${MEMLIMIT_CG}"
        fi
    fi
fi

export GOMEMLIMIT="${MEMLIMIT}MiB"

echo "Memory limit for Dataplaneapi: ${GOMEMLIMIT}"

exec /usr/local/bin/dataplaneapi -f=/usr/local/etc/haproxy/dataplaneapi.yml
