name: Version update check and release

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: update
  cancel-in-progress: false

jobs:
  main:
    runs-on: large_runner
    timeout-minutes: 30
    steps:
      - name: Check out repo
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Run a multi-line script
        id: build
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --local user.email "github-actions[bot]@haproxy.com"
          git config --local user.name "github-actions[bot]"
          ./build.sh
